### ISSUE TITLE
Evaluation Error: ReferenceError: renderHeatmapCalendar is not defined

### ISSUE THREAD

**Issue by oguera** [Richardsl/heatmap-calendar-obsidian#55]
Hi!
I just installed your plugin because it looks really neat and promising. However, as i copy&paste the example from the Readme i get the following error message:
```
Evaluation Error: ReferenceError: renderHeatmapCalendar is not defined
    at eval (eval at <anonymous> (plugin:dataview), <anonymous>:13:1)
    at DataviewInlineApi.eval (plugin:dataview:19673:16)
    at evalInContext (plugin:dataview:19674:7)
    at asyncEvalInContext (plugin:dataview:19684:32)
    at DataviewJSRenderer.render (plugin:dataview:19705:19)
    at DataviewRefreshableRenderer.maybeRefresh (plugin:dataview:19283:22)
    at t.e.tryTrigger (app://obsidian.md/app.js:1:1027924)
    at t.e.trigger (app://obsidian.md/app.js:1:1027857)
    at t.trigger (app://obsidian.md/app.js:1:1648741)
    at DataviewPlugin.eval (plugin:dataview:20688:76)
```

I'm using:
- Obsidian v1.0.3
- Dataview v0.5.47
- HeatmapCalendar v0.5.2

I restarted the application multiple times, but the error persists.

Thanks in advance for looking into this :v:

**Comment by oguera** [comment]
TIL: You have to enable every plugin that you installed because it's disabled by default. After enabling it obviously worked..
